global_costmap:
ros__parameters:
update_rate: 5.0
transform_tolerance: 0.5
plugin_names: ["static_layer","obstacle_layer","inflation_layer"]
plugin_types: ["nav2_costmap_2d::StaticLayer","nav2_costmap_2d::ObstacleLayer","nav2_costmap_2d::InflationLayer"]


local_costmap:
ros__parameters:
update_rate: 5.0
transform_tolerance: 0.5
plugin_names: ["obstacle_layer","inflation_layer"]
plugin_types: ["nav2_costmap_2d::ObstacleLayer","nav2_costmap_2d::InflationLayer"]


obstacle_layer:
ros__parameters:
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: "laser_frame", data_type: "LaserScan", topic: "/scan", marking: true, clearing: true, obstacle_range: 2.5, raytrace_range: 3.0}


inflation_layer:
ros__parameters:
inflation_radius: 0.55
